feat: ENS integration
dotbitHQ/denames pull request #17
Opened 2022-12-14 10:24 UTC by tianxiemaochiyu

2022-12-14 10:51 UTC, zgayjjf requested changes

2022-12-14 10:51 UTC, zgayjjf commented on src/errors/AllDIDError.ts
> +  DidIsInvalid = 'DidIsInvalid',
Seems not in use

2022-12-14 10:51 UTC, zgayjjf commented on src/services/EnsService.ts
> +  const BatchRequest = new Web3().BatchRequest
Can `ethers` replace this?

2022-12-14 10:51 UTC, zgayjjf commented on package.json
> +    "@ensdomains/ens": "^0.6.2",
Seems not in use.

2022-12-14 10:51 UTC, zgayjjf commented on src/services/EnsService.ts
> +    const tokenID: string = new BigNumber(labelhash(label)).toString(16)
`labelhash` is already hex, what's the purpose of BigNumber?

2022-12-16 02:51 UTC, zgayjjf requested changes

2022-12-21 05:17 UTC, zgayjjf requested changes

2022-12-21 05:17 UTC, zgayjjf commented on tests/services/ENSService.test.ts
> +      await expect(ensService.isSupported('abc.bit')).toBe(false)
Is `await` necessary?

2022-12-21 05:17 UTC, zgayjjf commented on tests/services/ENSService.test.ts
> +      expect(tokenId).toMatch(/^0x[0-9A-Fa-f]{64}$/)
`TokenId` of a specific name if fixed. So the test result should be a plain string.

2022-12-21 05:17 UTC, zgayjjf commented on src/services/EnsService.ts
> +  async addr (name: string): Promise<RecordItemAddr> {
The interface should be `addr(name: string, key: string)`.
Users can either pass in `coin_type` or `symbol` of the token.

2022-12-21 05:17 UTC, zgayjjf commented on tests/services/ENSService.test.ts
> +      const name = await ensService.addrs('0xC72B6f66017246d6A7f159F5C2BF358188AD9ECa')
Why is that invalid?

2022-12-21 07:05 UTC, tianxiemaochiyu commented on .eslintrc.js
> +  extends: 'plugin:blockabc/typescript',
Solve the problem that the `blockabc/typescript` shared configuration does not work under the VSCode editor

2022-12-23 04:47 UTC, zgayjjf requested changes

2022-12-23 04:47 UTC, zgayjjf commented on package.json
> +    "@ensdomains/ens-contracts": "^0.0.15",
What's the purpose of `@ensdomains/ens-contracts`?

2022-12-23 04:47 UTC, zgayjjf commented on tests/services/ENSService.test.ts
> +  describe('isSupported', () => {
Wrong test name

2022-12-23 04:48 UTC, zgayjjf commented on src/services/EnsService.ts
> +      ? this.isRegistered(name).then((isRegistered) => !isRegistered)
Where is Error thrown when unsupported?

2022-12-23 04:53 UTC, zgayjjf commented on src/services/EnsService.ts
> +function coinTypeOrcoinId2Symbol (coinType: string): string {
What is `coinId`? There seems to be no such thing.
Even if such a thing exists, the function's name should be `coinTypeOrCoinId2Symbol`. Pay attention to the Uppercase

2022-12-27 03:39 UTC, zgayjjf requested changes

2022-12-28 08:36 UTC, zgayjjf approved these changes

2022-12-28 13:17 UTC, merged